# Generated by Django 4.1.7 on 2023-03-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "trade",
                    models.CharField(
                        choices=[("F", "Free"), ("I", "Items"), ("M", "Money")],
                        default="F",
                        max_length=1,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main_app.item"
                    ),
                ),
            ],
        ),
    ]
