# Generated by Django 4.1.7 on 2023-03-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("level", models.IntegerField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name="request",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="request",
            name="date",
            field=models.DateField(verbose_name="Trade Request Date"),
        ),
    ]
