# Generated by Django 4.1.7 on 2023-03-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_player_alter_request_options_alter_request_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="players",
            field=models.ManyToManyField(to="main_app.player"),
        ),
    ]
